### ISSUE TITLE
[Simpler?] alternative

### ISSUE THREAD

**Issue by rejuvyesh** [martinseilair/dm_control2gym#1]
Didn't notice this before writing my own wrapper. Possibly of interest: 
https://github.com/rejuvyesh/gym-dmcontrol

Reasons for template based approach?

**Comment by martinseilair** [comment]
As you have noticed the template approach is obviously a very very dirty hack, that resulted from the ignorance of the possibility to pass kwargs  to the register function. It's out of the question that your approach is better. ;)
Thank you for noticing^^
